apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: iwyr1ahc6-go
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-go:de9272b1b3b61f5db5aea15ef6c26dce3e5ccc7f@sha256:4da099f0c1b94d445e85cba596a7d40206a00ed22797f831177e695ed7efbfbd
          name: container-image
